#pragma once
'Multimedia class scheduler API definitions

#define THREAD_ORDER_GROUP_INFINITE_TIMEOUT (-1LL)

enum _AVRT_PRIORITY
  AVRT_PRIORITY_LOW = -1
  AVRT_PRIORITY_NORMAL
  AVRT_PRIORITY_HIGH
  AVRT_PRIORITY_CRITICAL
end enum
type AVRT_PRIORITY as _AVRT_PRIORITY
type PAVRT_PRIORITY as _AVRT_PRIORITY ptr